# Generated by Django 3.2.16 on 2023-01-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_phone_number',
            new_name='phone_number',
        ),
    ]
