# Generated by Django 3.2.16 on 2023-01-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggyaccount', '0002_auto_20230122_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='wbalance',
        ),
    ]
