# Generated by Django 3.2.16 on 2023-01-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggyaccount', '0003_rename_amount_wallet_wbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='amount',
            new_name='abalance',
        ),
    ]
